import { Activity, AlertTriangle, BarChart3, Bell, Binary, Bot, Camera, Cloud, Globe2, Landmark, LineChart, Radar, Satellite, ShieldAlert, ShipWheel, Timer, TrendingUp } from "lucide-react";

export const classification = "UNCLASS // OSINT";

export const widgetCatalog = [
  { id: "latest-feed", type: "feed", title: "Latest Feed", icon: Activity },
  { id: "critical-feed", type: "feed", title: "Critical Updates", icon: AlertTriangle },
  { id: "nuclear-feed", type: "feed", title: "Nuclear Feed", icon: Binary },
  { id: "sanctions-feed", type: "feed", title: "Sanctions Feed", icon: Landmark },
  { id: "shipping-feed", type: "feed", title: "Shipping Feed", icon: ShipWheel },
  { id: "aviation-feed", type: "feed", title: "Aviation Feed", icon: Globe2 },
  { id: "cyber-feed", type: "feed", title: "Cyber Feed", icon: ShieldAlert },
  { id: "protests-feed", type: "feed", title: "Protest Feed", icon: Bell },
  { id: "humanitarian-feed", type: "feed", title: "Humanitarian Feed", icon: Cloud },
  { id: "coalition-feed", type: "feed", title: "Coalition Feed", icon: Radar },
  { id: "gulf-map", type: "map", title: "Gulf Map", icon: Globe2 },
  { id: "iran-map", type: "map", title: "Iran AOI Map", icon: Globe2 },
  { id: "flight-map", type: "map", title: "Flight Corridor", icon: Globe2 },
  { id: "shipping-map", type: "map", title: "Shipping Overlay", icon: ShipWheel },
  { id: "cyber-map", type: "map", title: "Cyber Heatmap", icon: ShieldAlert },
  { id: "satellite-map", type: "map", title: "Satellite BDA", icon: Satellite },
  { id: "escalation-chart", type: "chart", title: "Escalation Trend", icon: LineChart },
  { id: "oil-chart", type: "chart", title: "Oil Shock Curve", icon: TrendingUp },
  { id: "stock-chart", type: "chart", title: "Defense Stocks", icon: BarChart3 },
  { id: "protest-chart", type: "chart", title: "Civil Unrest Trend", icon: LineChart },
  { id: "shipping-chart", type: "chart", title: "Hormuz Flow", icon: LineChart },
  { id: "aviation-chart", type: "chart", title: "Airspace Density", icon: LineChart },
  { id: "kpi-threatcon", type: "kpi", title: "Threatcon", icon: ShieldAlert },
  { id: "kpi-escalation", type: "kpi", title: "Escalation %", icon: TrendingUp },
  { id: "kpi-alerts", type: "kpi", title: "Alert Count", icon: Bell },
  { id: "kpi-items", type: "kpi", title: "Items / 1h", icon: Activity },
  { id: "kpi-tplus", type: "kpi", title: "T+ Timer", icon: Timer },
  { id: "kpi-weather", type: "kpi", title: "Weather Risk", icon: Cloud },
  { id: "ai-morning", type: "ai_brief", title: "Morning Brief", icon: Bot },
  { id: "ai-executive", type: "ai_brief", title: "Executive Brief", icon: Bot },
  { id: "ai-forecast", type: "ai_brief", title: "Escalation Forecast", icon: Bot },
  { id: "webcam-tehran", type: "webcam", title: "Tehran Live", icon: Camera },
  { id: "webcam-hormuz", type: "webcam", title: "Hormuz Live", icon: Camera },
  { id: "orbat-coalition", type: "orbat", title: "Coalition ORBAT", icon: Radar },
  { id: "orbat-irgc", type: "orbat", title: "IRGC ORBAT", icon: Radar },
  { id: "bda-missile", type: "bda", title: "Missile BDA", icon: AlertTriangle },
  { id: "bda-port", type: "bda", title: "Port BDA", icon: AlertTriangle },
  { id: "ticker-oil", type: "ticker", title: "Oil Ticker", icon: TrendingUp },
  { id: "ticker-defense", type: "ticker", title: "Defense Ticker", icon: TrendingUp },
  { id: "ticker-fx", type: "ticker", title: "FX Stress", icon: TrendingUp },
  { id: "social-x", type: "social_pulse", title: "X Pulse", icon: Bell },
  { id: "social-keywords", type: "social_pulse", title: "Keyword Pulse", icon: Bell },
  { id: "weather-tehran", type: "weather", title: "Tehran Weather", icon: Cloud },
  { id: "weather-isfahan", type: "weather", title: "Isfahan Weather", icon: Cloud },
  { id: "weather-bandar", type: "weather", title: "Bandar Abbas Weather", icon: Cloud },
  { id: "timeline-ops", type: "timeline", title: "Operations Timeline", icon: Timer },
  { id: "timeline-nuclear", type: "timeline", title: "Nuclear Timeline", icon: Timer },
  { id: "alerts-stream", type: "alert_stream", title: "Alert Stream", icon: Bell },
  { id: "alerts-priority", type: "alert_stream", title: "Priority Alerts", icon: Bell },
  { id: "escalation-meter", type: "escalation", title: "Escalation Meter", icon: TrendingUp },
  { id: "escalation-forecast", type: "escalation", title: "Forecast Meter", icon: TrendingUp },
  { id: "satellite-heat", type: "satellite", title: "Thermal Watch", icon: Satellite },
  { id: "satellite-sar", type: "satellite", title: "SAR Watch", icon: Satellite },
  { id: "shipping-lanes", type: "shipping_lane", title: "Sea Lanes", icon: ShipWheel },
  { id: "shipping-insurance", type: "shipping_lane", title: "Insurance Risk", icon: ShipWheel },
  { id: "aviation-corridors", type: "aviation_tracker", title: "Corridor Tracker", icon: Globe2 },
  { id: "aviation-notams", type: "aviation_tracker", title: "NOTAM Risk", icon: Globe2 },
  { id: "cyber-threats", type: "cyber_heatmap", title: "Cyber Threat Grid", icon: ShieldAlert },
  { id: "cyber-outages", type: "cyber_heatmap", title: "Outage Radar", icon: ShieldAlert }
];
